# Site settings
title: Ultimate Jekyll Template
name: Jekyll Template
slogan: with a lot of ready to use features...
description: "KodGemisi Jekyll Template"

highlighter: pygments
timezone: Asia/Istanbul
permalink: /blog/:title
paginate_path: "blog/page:num"
paginate: 10

destination: '../static' # If this folder is inside the project then asset pipeline enters infinite loop
url: "http://ozg.com:4000"

# Build settings
markdown: kramdown # To make the template Github ready
assets:
  baseurl: 'http://ozg.com:4000/assets'
  js_compressor:  uglifier
  css_compressor: scss
  sources:
  - _assets
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets
  - _vendor

gems:
  - jekyll-compass
  - jekyll-assets
  - jekyll-assets/compass