# Site settings
title: Ultimate Jekyll Template
name: Your New Jekyll Site

highlighter: pygments
timezone: Asia/Istanbul
permalink: /blog/:title
paginate_path: "blog/page:num"
paginate: 11

email: selam@kodgemisi.com
description: "KodGemisi Jekyll Template"
destination: '../static' # If this folder is inside the project then asset pipeline enters infinite loop
url: "http://ozg.com:4000"

# Build settings
markdown: kramdown # To make the template Github ready
assets:
  baseurl: 'http://ozg.com:4000/assets'
  js_compressor:  uglifier
  css_compressor: scss
  sources:
  - _assets
  - _vendors
  - _assets/images
  - _assets/javascripts
  - _assets/stylesheets

gems:
  - jekyll-compass
  - jekyll-assets
  - jekyll-assets/compass